### ISSUE TITLE
Problem with SSH connection from windows using vscode

### ISSUE THREAD

**Issue by mai1015** [loft-sh/devpod#1191]
**What happened?**  
Trying to create a dev env with devpod and connect with vscode, but it never connect. vscode web is working fine.

Devpod desktop installed on my local windows 11
The docker is hosted on a Debian server 12 bookworm
Both connected through ssh provider

Logs:
```
[00:31:41.362] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59158 "vscode-remote-try-node-ssh.devpod" bash
[00:31:41.364] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[00:31:58.377] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\mai1015\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:500044)
	at Timeout._onTimeout (c:\Users\mai1015\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:619755)
	at listOnTimeout (node:internal/timers:573:17)
	at process.processTimers (node:internal/timers:514:7)
[00:31:58.381] ------

[00:32:02.484] > 00:32:02[38;5;6minfoWaiting for devpod agent to come up...
> ]0;C:\WINDOWS\System32\cmd.exe
[00:32:02.484] Got some output, clearing connection timeout
[00:32:02.502] > 00:32:02 [38;5;6minfo Waiting for devpod agent to come up...
[00:32:25.492] > 00:32:25 [38;5;6minfo Waiting for devpod agent to come up...
```

**What did you expect to happen instead?**  
The VScode should connect fine just like the vscode browser

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{"name":"Node.js","postCreateCommand":{"":["yarn install"]},"customizations":{"vscode":{"extensions":["streetsidesoftware.code-spell-checker"],"settings":{}}},"image":"mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye"}
```

**Local Environment:**  
- DevPod Version: v0.5.18
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: ssh

some related issue
https://github.com/loft-sh/devpod/issues/808#issuecomment-1935668762

**Comment by pascalbreuninger** [comment]
Hi @mai1015 and @FloSch62.
could you try to extend the SSH timeout option in VSCode itself and see if it resolves your issue please? https://stackoverflow.com/a/62423178

**Comment by mai1015** [comment]
I think it is not the problem of ssh as I connected to any other server perfectly fine. And the devpod agent should be up already as I tried the web version of vs code
