### ISSUE TITLE
Cannot open with VSCode

### ISSUE THREAD

**Issue by swznd** [loft-sh/devpod#1259]
**What happened?**  
Can't open workspace with VSCode, shows ECONNRESET, but with VSCode web working

```
> -e Connected to SSH Host - Please do not close this terminal
[03:05:36.766] Spawned SSH tunnel between local port 65012 and remote target socket /tmp/code-b7be2f3b-d251-4d87-9392-0d2172412176
[03:05:36.767] Waiting for ssh tunnel to be ready
[03:05:36.769] Tunneled socket /tmp/code-b7be2f3b-d251-4d87-9392-0d2172412176 to local port 65012
[03:05:36.769] Resolved "ssh-remote+app.devpod" to "port 65012"
[03:05:36.777] Initizing new exec server for ssh-remote+app.devpod
[03:05:36.777] Resolving exec server at port 65012
[03:05:36.809] Exec server for ssh-remote+app.devpod failed: Error: read ECONNRESET
[03:05:36.811] Resolver error: Error: read ECONNRESET
	at Socket.<anonymous> (/Users/fikri/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/extension.js:2:293965)
	at Object.onceWrapper (node:events:634:26)
	at Socket.emit (node:events:531:35)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[03:05:36.817] ------
```

**Local Environment:**  
- DevPod Version: 0.5.19
- Operating System: macOS Monterey 
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: ssh

**Anything else we need to know?** 
SSH provider with disabled builtin ssh option, also try using ssh provider with builtin ssh, but it shows error

**Comment by MartinAskestad** [comment]
Is plus `+` a valid character in hostnames? Maybe you can try to rename to `ssh-remote-app.devpod`?

**Comment by janekbaraniewski** [comment]
Hey @swznd thanks for reaching out! 

As @MartinAskestad pointed out, your host path is not valid. You'll need to fix it. 
If you still won't be able to connect to your workspace afterwards, please provide some more context so that I can reproduce it - how do you start your workspace, what devcontainer.json you're using etc.

**Comment by jlirochon** [comment]
Hi @bkneis,

I believe this should not be closed. I have the same problem, and I don't think it's related to a user chosen host path.

Using the following command : 
```
devpod up github.com/microsoft/vscode-remote-try-node --id myworkspace --reset --recreate --ide vscode
```

I get the same error :
```
[18:09:56.671] > /tmp/auth-agent922840795/listener.sock
> -e Connected to SSH Host - Please do not close this terminal
[18:09:56.672] Spawned SSH tunnel between local port 64131 and remote target socket /tmp/code-44364b64-cf08-4cf9-a1e8-1e46f4180395
[18:09:56.672] Waiting for ssh tunnel to be ready
[18:09:56.676] Tunneled socket /tmp/code-44364b64-cf08-4cf9-a1e8-1e46f4180395 to local port 64131
[18:09:56.676] Resolved "ssh-remote+myworkspace.devpod" to "port 64131"
[18:09:56.682] Initizing new exec server for ssh-remote+myworkspace.devpod
[18:09:56.682] Resolving exec server at port 64131
[18:09:56.688] Exec server for ssh-remote+myworkspace.devpod failed: Error: read ECONNRESET
[18:09:56.689] Resolver error: Error: read ECONNRESET
	at Socket.<anonymous> (/Users/julien/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:293969)
	at Object.onceWrapper (node:events:634:26)
	at Socket.emit (node:events:531:35)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[18:09:56.692] ------
```

**Local environment** :
- DevPod Version: 0.5.21 | darwin | aarch64
- Operating System : macOS Sonoma 14.7
- Chip : Apple M1

**Provider** : Docker Desktop 4.34.2

**The exact same command works on my other systems** :
- ubuntu 24.04.1 / Intel
- macOS Ventura 13.7 / Intel
