### ISSUE TITLE
AppImage not running on Fedora 41

### ISSUE THREAD

**Issue by nfa04** [loft-sh/devpod#1410]
**What happened?**  
I downloaded the AppImage from the Website, gave it permission to be executed and ran it. It showed only a white screen, while when after closing it, it doesn't open again. I made sure all dependencies are installed as described on the installation guide.

**What did you expect to happen instead?**  
The UI should show up.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run Fedora 41, try to open the AppImage.

My *`devcontainer.json`*:
Doesn't exist yet.

**Local Environment:**  
- 

**DevPod Provider:**  
None yet.

**Comment by gokhangeyik** [comment]
Here is the AppImage console output in Fedora 41

```
Gtk-Message: 19:37:30.173: Failed to load module "appmenu-gtk-module": 'gtk_module_display_init': /usr/lib64/gtk-3.0/modules/libwindow-decorations-gtk-module.so: undefined symbol: gtk_module_display_init
/usr/bin/xdg-mime: line 885: qtpaths: command not found
Gtk-Message: 19:37:31.110: Failed to load module "appmenu-gtk-module": 'gtk_module_display_init': /usr/lib64/gtk-3.0/modules/libwindow-decorations-gtk-module.so: undefined symbol: gtk_module_display_init
**Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...**
```

**Comment by swaiku** [comment]
I do have this error as well with fedora 41. With some research i found out that a lot of other apps have the same problems. like :

GitButler : https://github.com/gitbutlerapp/gitbutler/issues/5282

It looks like the issue come from webkit itself : https://www2.webkit.org/show_bug.cgi?id=280239

downgrade dependency look like the temporary solution.

**Comment by lzajka** [comment]
I'm using Arch and had to downgrade to:
- `mesa-1:24.1.0-1`
- `llvm-libs:17.0.6-2`

**Comment by fpoirotte** [comment]
> I'm using Arch and had to downgrade to:
> 
>     * `mesa-1:24.1.0-1`
> 
>     * `llvm-libs:17.0.6-2`

Thank you for your reply.

We were facing the same issue on Fedora 40 and downgrading mesa (`sudo dnf downgrade mesa-libEGL-24.0.5-1.fc40.x86_64`, which will also downgrade other packages related to mesa) allowed us to start devpod once again until a better solution can be found.

**Comment by nfa04** [comment]
Thanks for your help, unfortunately mesa-libEGL-0:24.2.4-1 is the oldest version available in the fedora 41 repos. I'm still hoping for a fix soon, but at the moment thankfully don't really need it.

**Comment by stdevel** [comment]
This also applies to Fedora 40 as well:

```
Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

```command
$ rpm -qa|grep EGL
mesa-libEGL-24.1.7-1.fc40.x86_64
mesa-libEGL-devel-24.1.7-1.fc40.x86_64
mesa-libEGL-24.1.7-1.fc40.i686
```

**Comment by lombervid** [comment]
I'm getting this on Fedora 41 KDE:

```
/usr/bin/xdg-mime: line 885: qtpaths: command not found

** (WebKitWebProcess:93347): WARNING **: 11:48:57.901: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
[/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.2/src/linux.rs:104:29] buffer = "version"
thread '<unnamed>' panicked at src/workspaces.rs:175:72:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x558900aac0da - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha4a311b32f6b4ad8
   1:     0x558900adb8b3 - core::fmt::write::h1866771663f62b81
   2:     0x558900aa7063 - std::io::Write::write_fmt::hb549e7444823135e
   3:     0x558900aabf22 - std::sys::backtrace::BacktraceLock::print::hddd3a9918ce29aa7
   4:     0x558900aad1dc - std::panicking::default_hook::{{closure}}::h791f75256b902d7d
   5:     0x558900aad022 - std::panicking::default_hook::h82cc572fcb0d8cd7
   6:     0x558900aad7b7 - std::panicking::rust_panic_with_hook::he21644cc2707f2c4
   7:     0x558900aad64a - std::panicking::begin_panic_handler::{{closure}}::h42f7c414fed3cad9
   8:     0x558900aac5b9 - std::sys::backtrace::__rust_end_short_backtrace::ha26cf5766b4e8c65
   9:     0x558900aad2dc - rust_begin_unwind
  10:     0x5588ffb29f30 - core::panicking::panic_fmt::h74866b78e934b1c0
  11:     0x5588ffb2a376 - core::result::unwrap_failed::h899ed7ab2ccb8159
  12:     0x5588ffeecf5f - std::sys::backtrace::__rust_begin_short_backtrace::h65aab9bfb1572dfe
  13:     0x5588ffc7ca74 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h516ceddbb71339f7
  14:     0x558900ab3dbb - std::sys::pal::unix::thread::Thread::new::thread_start::h14f1eb868ff90fc9
  15:     0x7f2390f98168 - start_thread
  16:     0x7f239101c14c - __clone3
  17:                0x0 - <unknown>
```

**Comment by vorburger** [comment]
Just FYI, as a workaround until this gets fixed, I've been able to start DevPod on Fedora by [using the Targz](https://devpod.sh/docs/getting-started/install#install-devpod) instead of the AppImage, [after a](https://github.com/loft-sh/devpod/pull/1618/) `sudo dnf install libappindicator-gtk3` to fix this:

```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libappindicator-sys-0.9.0/src/lib.rs:41:5:
Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Piotr1215** [comment]
Same error happens on Ubuntu (pop os). The workaround proposed by @vorburger worked for me too.

**Comment by AverageHelper** [comment]
not stale

**Comment by AverageHelper** [comment]
still not stale

**Comment by kagesenshi** [comment]
also fails on fedora 42

**Comment by mberndt123** [comment]
Also, why does the app not crash when it fails to create the main window? Oh, I know why: because ignoring errors is the default behaviour in Go 🙄

**Comment by moemoeq** [comment]
Still having same issue on Fedora 43

**Comment by voznik** [comment]
version v0.7.0-alpha.34 on Arch fails with the same issue 

```
Gtk-Message: 13:59:02.715: Failed to load module "appmenu-gtk-module"
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

Works when using "tar.gz" way with prebuild executables

**Comment by skevetter** [comment]
Any chance you would try out my release to see if the issue appears https://github.com/skevetter/devpod/releases

**Comment by masakk1** [comment]
Running the AppImage on Bluefin, still dead.

```
~/Downloads 
❯ ./DevPod_linux_amd64.AppImage 

** (WebKitWebProcess:10842): WARNING **: 16:31:17.940: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

The window opens, but it's just blank.

**Comment by skevetter** [comment]
> Running the AppImage on Bluefin, still dead.
> 
> ```
> ~/Downloads 
> ❯ ./DevPod_linux_amd64.AppImage 
> 
> ** (WebKitWebProcess:10842): WARNING **: 16:31:17.940: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
> Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
> ```
> 
> The window opens, but it's just blank.

Thank you for providing the log output from your attempt. This is an issue that I am tracking and working on. You are welcome to attempt some of the suggestions provided in [similar issues](https://github.com/skevetter/devpod/issues) while a fix is worked on.

**Comment by masakk1** [comment]
> Thank you for providing the log output from your attempt. This is an issue that I am tracking and working on. You are welcome to attempt some of the suggestions provided in [similar issues](https://github.com/skevetter/devpod/issues) while a fix is worked on.

I'm not really sure what I'm looking for exactly.

If anything, it seems like the AppImage has distro-specific errors? I tried running it in an arch distrobox and it seems to run correctly, but It's a little un-usable because some links are broken and opening the wrong vscode - I think that's an issue with distrobox itself, nothing that should concern devpod.

I can do more testing if you need!

**Comment by AverageHelper** [comment]
Not stale.

fwiw, I mainly use the Flatpak, but tried running the AppImage just now and nothing launched. There was no apparent feedback from the program unless I tried to launch via the terminal, which helpfully reported this:

```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

It may be worth noting that `fuse` version 2.9.9 is installed on my Fedora Kinoite system, according to `rpm -qi fuse`

**Comment by skevetter** [comment]
@AverageHelper do you want to check out my fork? I have not heard any devs report having AppImage-specific issues with my releases as of late. I figure it might be worth trying out.
