### ISSUE TITLE
DevPod errors on startup with golang binary in the container crashing when using vscode web.

### ISSUE THREAD

**Issue by davenull** [loft-sh/devpod#394]
**What happened?**  

```
[15:22:09] fatal error retrieving container status: panic: runtime error: invalid memory address or nil pointer dereference goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x65
github.com/loft-sh/devpod/cmd.Execute.func1()
        /home/runner/work/devpod/devpod/cmd/root.go:61 +0x3d
panic({0x132a060, 0x20787e0})
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212
github.com/loft-sh/devpod/pkg/agent.rerunAsRoot(0x0, {0x1747b48, 0xc0000ca180})
        /home/runner/work/devpod/devpod/pkg/agent/agent.go:242 +0xf4
github.com/loft-sh/devpod/pkg/agent.ReadAgentWorkspaceInfo({0x0?, 0x40dea7?}, {0x7ffddf045e07?, 0x76f9c6?}, {0x7ffddf045df6?, 0xc00063fc58?}, {0x1747b48, 0xc0000ca180})
        /home/runner/work/devpod/devpod/pkg/agent/agent.go:148 +0x8e
github.com/loft-sh/devpod/cmd/agent/workspace.(*StatusCmd).Run(0xc0000ca800?, {0x173ab38, 0xc0000b8010}, {0x1747b48, 0xc0000ca180})
        /home/runner/work/devpod/devpod/cmd/agent/workspace/status.go:42 +0x7a
github.com/loft-sh/devpod/cmd/agent/workspace.NewStatusCmd.func1(0xc0004c4000?, {0xc00007e440?, 0x4?, 0x4?})
        /home/runner/work/devpod/devpod/cmd/agent/workspace/status.go:32 +0x51
github.com/spf13/cobra.(*Command).execute(0xc0004c4000, {0xc00007e400, 0x4, 0x4})
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000544c00)
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
github.com/loft-sh/devpod/cmd.Execute()
        /home/runner/work/devpod/devpod/cmd/root.go:71 +0x59
main.main()
        /home/runner/work/devpod/devpod/main.go:12 +0xca

exit status 1
```

**What did you expect to happen instead?**  
devpod working

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Spin up a workspace. 

My *`devcontainer.json`*:
```
{"image":"mcr.microsoft.com/devcontainers/base:ubuntu","build":{}}

```

**Local Environment:**  
- DevPod Version: v0.1.9
- Operating System:  mac
- ARCH of the OS:  ARM64

**DevPod Provider:**  
- Cloud Provider: Civo
- Kubernetes Provider: v1.27.2
- Local/remote provider:  ssh

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
@davenull thanks for creating this issue! I opened up a PR to address this issue
