### ISSUE TITLE
Permission issues with podman

### ISSUE THREAD

**Issue by simon511000** [loft-sh/devpod#413]
**What happened?**
Unable to create a workspace due to permission issues.

```
[12:49:33] info Creating devcontainer...
[12:49:33] info Clonage dans '/var/home/simon/.devpod/agent/contexts/default/workspaces/vscode-remote-try-node/content'...
[12:49:34] info 27fe70e6e10374be32ff68f5385bcdae652b12bec3b4d9d2efcc133cf71fc92c
[12:49:36] info Setup container...
[12:49:36] info Chown workspace...
[12:49:36] info open /workspaces/vscode-remote-try-node: permission denied
[12:49:36] info Run command: yarn install...
[12:49:36] info yarn install v1.22.19
[12:49:36] info Error: EACCES: permission denied, open '/workspaces/vscode-remote-try-node/package.json'
[12:49:36] info at Object.openSync (node:fs:601:3)
[12:49:36] info at Object.readFileSync (node:fs:469:35)
[12:49:36] info at onUnexpectedError (/opt/yarn-v1.22.19/lib/cli.js:88615:106)
[12:49:36] info at /opt/yarn-v1.22.19/lib/cli.js:88734:9
[12:49:36] info Failed running command: exit status 1
[12:49:36] info post create commands: exit status 1
```

**What did you expect to happen instead?**
I expect to be able to create and use a workspace without any permission issues.

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. Create a docker provider with Docker Path set as `podman`
2. Create a workspace with any quickstart example (I tried NodeJS and Rust)

**Local Environment:**

* DevPod Version: `v0.1.9` installed with `rpm-ostree`
* Operating System: Fedora Silverblue
* ARCH of the OS: `AMD64`

**DevPod Provider:**

* Local/remote provider: docker (podman)

**Comment by 89luca89** [comment]
Hi @simon511000 thanks for reporting I'll take a look :+1:

**Comment by pascalbreuninger** [comment]
@bagashiz is this still an issue for you with the latest version of DevPod?

**Comment by bagashiz** [comment]
@pascalbreuninger sorry, I switched to docker and haven't tried using it with podman again.

**Comment by pascalbreuninger** [comment]
Alright, I'll close this ticket then. Let me know if anyone else can reproduce the error

**Comment by andrii-kriachko** [comment]
similar issue

<img width="1882" height="99" alt="Image" src="https://github.com/user-attachments/assets/c79f7cc1-299a-4720-aa20-5b05a9abcd69" />

got that issue when tried to work with simple compose file
