### ISSUE TITLE
nil pointer dereference docker remote

### ISSUE THREAD

**Issue by dcharbonnier** [loft-sh/devpod#446]
```
[08:04:06] debug panic: runtime error: invalid memory address or nil pointer dereference goroutine 1 [running]:
[08:04:06] debug runtime/debug.Stack()
[08:04:06] debug /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/debug/stack.go:24 +0x65
[08:04:06] debug github.com/loft-sh/devpod/cmd.Execute.func1()
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/root.go:61 +0x3d
[08:04:06] debug panic({0x132e300, 0x2080840})
[08:04:06] debug /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212
[08:04:06] debug github.com/loft-sh/devpod/pkg/devcontainer/metadata.GetImageMetadataFromContainer(0x20da9b0?, 0x0?, {0x174cb50?, 0xc0001ed1a0?})
[08:04:06] debug /home/runner/work/devpod/devpod/pkg/devcontainer/metadata/metadata.go:90 +0x28
[08:04:06] debug github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runDockerCompose(0xc0004b0230, 0xc0005246e0, {{0x20da9b0?, 0x174cb50?, 0xc0001ed1a0?}, 0x70?, 0x65?, 0x74?})
[08:04:06] debug /home/runner/work/devpod/devpod/pkg/devcontainer/compose.go:107 +0x4cf
[08:04:06] debug github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up(0xc0004b0230, {{0x20da9b0?, 0xc0001ed1a0?, 0x0?}, 0x0?, 0x0?, 0x0?})
[08:04:06] debug /home/runner/work/devpod/devpod/pkg/devcontainer/run.go:131 +0x16f
[08:04:06] debug github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp(0xc00043ae80, 0x0?, {0x174cb50?, 0xc0001ed1a0?})
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:374 +0x58
[08:04:06] debug github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up(0x173fbc0?, {0x173fbf8, 0xc0000420c8}, 0xc0001e8000?, {0x1745c60, 0xc0001eac40}, {0x174cb50?, 0xc0001ed1a0?})
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:164 +0x50
[08:04:06] debug github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run(0xc00043ae80, {0x173fbf8, 0xc0000420c8})
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:98 +0x1cc
[08:04:06] debug github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1(0xc0004f4c00?, {0xc0003f5e00?, 0x3?, 0x3?})
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:60 +0x2b
[08:04:06] debug github.com/spf13/cobra.(*Command).execute(0xc0004f4c00, {0xc0003f5cb0, 0x3, 0x3})
[08:04:06] debug /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916 +0x862
[08:04:06] debug github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f4300)
[08:04:06] debug /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
[08:04:06] debug github.com/spf13/cobra.(*Command).Execute(...)
[08:04:06] debug /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
[08:04:06] debug github.com/loft-sh/devpod/cmd.Execute()
[08:04:06] debug /home/runner/work/devpod/devpod/cmd/root.go:71 +0x59
[08:04:06] debug main.main()
[08:04:06] debug /home/runner/work/devpod/devpod/main.go:12 +0xca
[08:04:06] debug Done executing up command
[08:04:06] debug Done creating devcontainer
```

**Comment by lizardruss** [comment]
@dcharbonnier Thanks for reporting this issue. Can you reproduce this, and if so can you provide the log output from before the panic?

If would also be helpful if you could provide your `.devcontainer.json` and `docker-compose.yaml` if possible. I'd like to reproduce this error before attempting a fix.

**Comment by lizardruss** [comment]
@dcharbonnier Does this still occur with the latest release?

**Comment by lizardruss** [comment]
Closing due to inactivity. Please reopen if it occurs again.
