### ISSUE TITLE
Bug:failure to connect to devops-cli inside devpod container

### ISSUE THREAD

**Issue by d3287t328** [loft-sh/devpod#484]
**What happened?**

When I launch my workspace it fails with the following ssh failures. It appears that the workspace is looking for devpod-cli inside the container but the command can be found on the host os (Fedora latest):

```
[12:24:37.492] stderr> kex_exchange_identification: Connection closed by remote host
[12:24:37.492] stderr> Connection closed by UNKNOWN port 65535
[12:24:37.494] > local-server-1> ssh child died, shutting down
[12:24:37.540] Local server exit: 0
[12:24:37.541] Received install output: local-server-1> Running ssh connection command: "-v -T -D 45925 -o ConnectTimeout=15 vscode@tws-api.devpod"
local-server-1> Spawned ssh, pid=195
OpenSSH_9.3p1, OpenSSL 3.0.8 7 Feb 2023
/bin/sh: line 1: /usr/bin/devpod-cli: No such file or directory
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
local-server-1> ssh child died, shutting down

[12:24:37.542] Failed to parse remote port from server output
[12:24:37.553] Resolver error: Error: 
	at m.Create (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /home/a/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
	```
```

which devpod-cli
/usr/bin/devpod-cli

```

**What did you expect to happen instead?**  
Expected workspace env to open successfully.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:

I do not have this, I launched the workspace it straight from the GUI app.

**Local Environment:**  
- DevPod Version: 0.2.0
- Operating System: linux fedora
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: docker

**Anything else we need to know?**  

My vs code is running from a Flatpak binary and has shell access defined in the settings.json that work correctly.
```

**Comment by pascalbreuninger** [comment]
Hi @d3287t328 , thank you for opening the issue, we'll look into it. 
Could you paste the devpod logs here as well please? You can get more detailed output by enabling the `--debug` flag from the UI settings or using it with `devpod up`

**Comment by pascalbreuninger** [comment]
closing due to staleness, feel free to reopen if you can still repro

**Comment by pinei** [comment]
I had the same problem here on Pop OS when VSCode was installed as a Flatpak package.

It was solved after reinstalling vscode via .deb package.
