### ISSUE TITLE
I can not open with vscode

### ISSUE THREAD

**Issue by justinbuzzni** [loft-sh/devpod#491]
**What happened?**  
[22:55:28.685] stderr> [0;1;37m22:55:28 [0;1;36minfo find dev container: docker ps: exec: "docker": executable file not found in $PATH
[22:55:28.685] stderr> [0;1;37m22:55:28 [0;1;31merror Error tunneling to container: Process exited with status 1
[22:55:29.465] stderr> [0;1;37m22:55:29 [0;1;31mfatal tunnel to container: run in container: ssh: handshake failed: EOF
[22:55:29.467] stderr> kex_exchange_identification: Connection closed by remote host
[22:55:29.468] stderr> Connection closed by UNKNOWN port 65535
[22:55:29.468] > local-server-1> ssh child died, shutting down
[22:55:29.474] Local server exit: 0
[22:55:29.474] Received install output: local-server-1> Running ssh connection command: "-v -T -D 65165 -o ConnectTimeout=15 embedchain.devpod"
local-server-1> Spawned ssh, pid=56823
OpenSSH_9.0p1, LibreSSL 3.3.6
[0;1;37m22:55:28 [0;1;36minfo find dev container: docker ps: exec: "docker": executable file not found in $PATH
[0;1;37m22:55:28 [0;1;31merror Error tunneling to container: Process exited with status 1
[0;1;37m22:55:29 [0;1;31mfatal tunnel to container: run in container: ssh: handshake failed: EOF
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
local-server-1> ssh child died, shutting down

[22:55:29.475] Failed to parse remote port from server output
[22:55:29.479] Resolver error: Error: 
	at m.Create (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/namsangboy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[22:55:29.488] ------

**What did you expect to happen instead?**  
I expected to open vscode. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{"image":"mcr.microsoft.com/devcontainers/python:3","build":{}}
```

**Local Environment:**  
- DevPod Version: v0.2.1-beta.0
- Operating System:  mac
- ARCH of the OS: ARM64   

**DevPod Provider:**  
- Local/remote provider: docker 

**Anything else we need to know?**  
I can open with vscode browser. but vscode not work

**Comment by FabianKramm** [comment]
@justinbuzzni thanks for creating this issue! And docker is running locally and in the path, so something like:
```
sh -c "docker ps"
```
works?

**Comment by justinbuzzni** [comment]
`CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS     NAMES
6451e4a0e314   mcr.microsoft.com/devcontainers/python:3   "/bin/sh -c 'echo Co…"   53 minutes ago   Up 53 minutes             crazy_chandrasekhar
204013c7cbba   mcr.microsoft.com/devcontainers/python:3   "/bin/sh -c 'echo Co…"   56 minutes ago   Up 56 minutes             silly_banzai`

I download latest version v0.2.1. It works well. 

Thank you
