### ISSUE TITLE
Unable to attach vs code to workspace using ssh

### ISSUE THREAD

**Issue by RashiqAzhan** [loft-sh/devpod#604]
**What happened?**  
Can't connect to the workspace using SSH using the "Remote - SSH" extension of Visual Studio Code. I've tried vscodium, oss, & the official code.

**What did you expect to happen instead?**  
The editor should connect and I'd be able to browse all the folders in the containers.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Open a workspace using any repo and try attaching a vs code manually by starting the workspace with the 'None' option.

My *`devcontainer.json`*:
```
{
    "image":"mcr.microsoft.com/devcontainers/python:3",
    "build":{}
}
```

**Local Environment:**  
- DevPod Version: 0.3.4
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  
The container is connecting to jetbrains product.

**Comment by neogopher** [comment]
Hi @RashiqAzhan :wave: ,
Thanks for creating the issue. :slightly_smiling_face: 
Do you see any error messages when you manually connect VS Code using the Remote-SSH Extension. Also what hostname are you using for the connection. It should usually be of the format `<workspace-name>.devpod` and you will see this towards the end of the log output when you start the workspace.

**Comment by RashiqAzhan** [comment]
@neogopher thank you for the quick reply. Apologies for not including the error messages. I had them on the clipboard but promptly forgot to include them. I've updated the original post with the terminal outputs.

I can see `<workspace-name>.devpod`.  I can manually ssh into it in the terminal but not with vs code only for some reason.

**Comment by neogopher** [comment]
Hi @RashiqAzhan , 
In the error log, we can see OpenSSH version mismatch. Does this show up in all workspaces which you create this way.
```
[18:12:20.025] Checking ssh with "ssh -V"
[18:12:20.032] > OpenSSL version mismatch. Built against 30100010, you have 30000020
```

I tried to replicate the issue by anchoring to the same versions as yours for both VSCode as well as the remoteSSH extension, but could not. 

Can you try a different source image for the workspace, reinstalling remote-ssh extension etc.

**Comment by neogopher** [comment]
Hi @RashiqAzhan ,
Just wanted to check if you were able to try the above or were able to fix the issue by any other way.

**Comment by RashiqAzhan** [comment]
@neogopher Sorry for the late feedback. I had resorted back to the local install.

This is my current OpenSSH version `OpenSSH_9.4p1, OpenSSL 3.1.2 1 Aug 2023` and the error message has changed.
```bash
[16:44:10.108] Log Level: 2
[16:44:10.109] SSH Resolver called for "ssh-remote+c-sharp-play-ground.devpod", attempt 1
[16:44:10.110] "remote.SSH.useLocalServer": true
[16:44:10.110] "remote.SSH.path": undefined
[16:44:10.111] "remote.SSH.configFile": undefined
[16:44:10.111] "remote.SSH.useFlock": true
[16:44:10.111] "remote.SSH.lockfilesInTmp": false
[16:44:10.111] "remote.SSH.localServerDownload": auto
[16:44:10.111] "remote.SSH.remoteServerListenOnSocket": false
[16:44:10.111] "remote.SSH.showLoginTerminal": false
[16:44:10.112] "remote.SSH.defaultExtensions": []
[16:44:10.112] "remote.SSH.loglevel": 2
[16:44:10.112] "remote.SSH.enableDynamicForwarding": true
[16:44:10.112] "remote.SSH.enableRemoteCommand": false
[16:44:10.112] "remote.SSH.serverPickPortsFromRange": {}
[16:44:10.112] "remote.SSH.serverInstallPath": {}
[16:44:10.118] VS Code version: 1.81.1
[16:44:10.118] Remote-SSH version: remote-ssh@0.102.0
[16:44:10.118] linux x64
[16:44:10.122] SSH Resolver called for host: c-sharp-play-ground.devpod
[16:44:10.122] Setting up SSH remote "c-sharp-play-ground.devpod"
[16:44:10.124] Acquiring local install lock: /tmp/vscode-remote-ssh-fc3bdcf0-install.lock
[16:44:10.124] Looking for existing server data file at /home/user/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fc3bdcf0-aef377c42cea6e9aea642829953104f07097abfa-0.102.0/data.json
[16:44:10.124] Using commit id "aef377c42cea6e9aea642829953104f07097abfa" and quality "stable" for server
[16:44:10.126] Install and start server if needed
[16:44:10.128] PATH: /home/user/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/.local/share/JetBrains/Toolbox/scripts
[16:44:10.128] Checking ssh with "ssh -V"
[16:44:10.137] > OpenSSH_9.4p1, OpenSSL 3.1.2 1 Aug 2023

[16:44:10.139] askpass server listening on /run/user/1000/vscode-ssh-askpass-46a480ef905e9ccf5180130eeb4f35b9a8df819c.sock
[16:44:10.139] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-c8a57f5cc74481f391e14dafe128e9c82dc96837.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35855","-o","ConnectTimeout=15","c-sharp-play-ground.devpod"],"serverDataFolderName":".vscodium-server","dataFilePath":"/home/user/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fc3bdcf0-aef377c42cea6e9aea642829953104f07097abfa-0.102.0/data.json"}
[16:44:10.139] Local server env: {"SSH_AUTH_SOCK":"/tmp/ssh-XXXXXXdU5PzE/agent.4267","SHELL":"/bin/fish","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/vscodium-bin/codium","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-46a480ef905e9ccf5180130eeb4f35b9a8df819c.sock"}
[16:44:10.143] Spawned 32382
[16:44:10.227] > local-server-1> Running ssh connection command: "-v -T -D 35855 -o ConnectTimeout=15 c-sharp-play-ground.devpod"
[16:44:10.231] > local-server-1> Spawned ssh, pid=32432
[16:44:10.234] stderr> OpenSSH_9.4p1, OpenSSL 3.1.2 1 Aug 2023
[16:44:10.841] stderr> debug1: Server host key: ssh-rsa SHA256:5XutAYvkN9dmdTaujwxdqplocozz10nbTINrtOYoGkc
[16:44:10.841] stderr> Warning: Permanently added 'c-sharp-play-ground.devpod' (RSA) to the list of known hosts.
[16:44:10.843] stderr> Authenticated to c-sharp-play-ground.devpod (via proxy) using "none".
[16:44:10.846] > ready: 208bacb878b2
[16:44:10.847] > Linux 6.5.1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Sep 2023 17:22:15 +0000
[16:44:10.847] Platform: linux
[16:44:10.848] > /bin/bash
[16:44:10.848] Shell: bash
[16:44:10.848] Creating bash subshell inside "bash"
[16:44:10.849] > bash version:  5.1.4(1)-release
[16:44:10.857] > 208bacb878b2: running
[16:44:10.883] > Acquiring lock on /home/vscode/.vscodium-server/bin/aef377c42cea6e9aea642829953104f07097abfa/vscode-remote-lock.vscode.aef377c42cea6e9aea642829953104f07097abfa
[16:44:10.886] > Installing to /home/vscode/.vscodium-server/bin/aef377c42cea6e9aea642829953104f07097abfa...
[16:44:10.888] > 208bacb878b2%%1%%
[16:44:10.891] > Downloading with wget
[16:44:11.220] > wget download failed
> https://update.code.visualstudio.com/commit:aef377c42cea6e9aea642829953104f07097abfa/server-linux-x64/stable: 2023-09-19 10:44:11 ERROR 404: Not Found.
> printenv:
[16:44:11.221] >     SHELL=/bin/bash
>     NUGET_XMLDOC_MODE=skip
>     HOSTNAME=d30f512ea79b
>     SSH_AUTH_SOCK=/tmp/auth-agent815961737/listener.sock
>     DOTNET_VERSION=7.0.11
>     ASPNETCORE_URLS=
>     PWD=/home/vscode/.vscodium-server/bin/aef377c42cea6e9aea642829953104f07097abfa
>     LOGNAME=vscode
>     POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-DotnetSDK-Debian-11
>     HOME=/home/vscode
>     NVM_SYMLINK_CURRENT=true
>     VSCODE_AGENT_FOLDER=/home/vscode/.vscodium-server
>     DOTNET_SDK_VERSION=7.0.401
>     NVM_DIR=/usr/local/share/nvm
>     DOTNET_GENERATE_ASPNET_CERTIFICATE=false
>     USER=vscode
>     SHLVL=1
>     ASPNET_VERSION=7.0.11
>     DOTNET_NOLOGO=true
>     DOTNET_RUNNING_IN_CONTAINER=true
>     DOTNET_USE_POLLING_FILE_WATCHER=true
>     PATH=/usr/local/share/nvm/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.dotnet:/home/vscode/.dotnet/tools
>     MAIL=/var/mail/vscode
>     OLDPWD=/home/vscode
>     _=/usr/bin/printenv
[16:44:11.222] > Trigger local server download
> 208bacb878b2:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/vscode/.vscodium-server/bin/==
> destFolder2==aef377c42cea6e9aea642829953104f07097abfa==
> 208bacb878b2:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/vscode/.vscodium-server/bin/aef377c42cea6e9aea642829953104f07097abfa/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[16:44:11.222] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/vscode/.vscodium-server/bin/aef377c42cea6e9aea642829953104f07097abfa"}
[16:44:11.222] Downloading VS Code server locally...
[16:44:11.977] Terminating local server
[16:44:11.978] Resolver error: Error: Server returned 404
    at f (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:658:34781)
    at T.download (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:659:1732)
[16:44:11.979] ------
```

This issue is no longer occurring on microsofts VS code. Both OSS and Vscodium show the same issue of wget failing to download and ending with a 404. Are those now supported as of now?

I have created a new workspace after updating devpod and reinstalled the remote-ssh extension across all the IDE's.

**Comment by Priyanka-Inflectionzone** [comment]
[18:17:31.663] Log Level: 1
[18:17:31.678] SSH Resolver called for "ssh-remote+xxxx-workspace.devpod", attempt 1
[18:17:31.678] "remote.SSH.useLocalServer": false
[18:17:31.679] "remote.SSH.useExecServer": true
[18:17:31.679] "remote.SSH.showLoginTerminal": false
[18:17:31.679] "remote.SSH.remotePlatform": {}
[18:17:31.680] "remote.SSH.path": undefined
[18:17:31.680] "remote.SSH.configFile": C:\Users\rajve\.ssh\config
[18:17:31.685] "remote.SSH.useFlock": true
[18:17:31.685] "remote.SSH.lockfilesInTmp": false
[18:17:31.688] "remote.SSH.localServerDownload": auto
[18:17:31.688] "remote.SSH.remoteServerListenOnSocket": false
[18:17:31.688] "remote.SSH.showLoginTerminal": false
[18:17:31.688] "remote.SSH.defaultExtensions": []
[18:17:31.689] "remote.SSH.loglevel": 1
[18:17:31.689] "remote.SSH.enableDynamicForwarding": true
[18:17:31.692] "remote.SSH.enableRemoteCommand": false
[18:17:31.692] "remote.SSH.serverPickPortsFromRange": {}
[18:17:31.692] "remote.SSH.serverInstallPath": {}
[18:17:31.771] VS Code version: 1.91.0
[18:17:31.771] Remote-SSH version: remote-ssh@0.112.0
[18:17:31.771] win32 x64
[18:17:31.789] SSH Resolver called for host: xxxx-workspace.devpod
[18:17:31.789] Setting up SSH remote "xxxx-workspace.devpod"
[18:17:31.801] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0a7286" and quality "stable" for server
[18:17:31.805] Install and start server if needed
[18:17:34.299] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[18:17:34.303] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[18:17:34.303] Checking ssh with "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe -V"
[18:17:34.307] Got error from ssh: spawn C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe ENOENT
[18:17:34.308] Checking ssh with "C:\windows\ssh.exe -V"
[18:17:34.310] Got error from ssh: spawn C:\windows\ssh.exe ENOENT
[18:17:34.311] Checking ssh with "C:\Users\rajve\OneDrive\Documents\kube-demo\kubectl.exe\ssh.exe -V"
[18:17:34.312] Got error from ssh: spawn C:\Users\rajve\OneDrive\Documents\kube-demo\kubectl.exe\ssh.exe ENOENT
[18:17:34.313] Checking ssh with "C:\windows\System32\Wbem\ssh.exe -V"
[18:17:34.314] Got error from ssh: spawn C:\windows\System32\Wbem\ssh.exe ENOENT
[18:17:34.315] Checking ssh with "C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[18:17:34.316] Got error from ssh: spawn C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[18:17:34.316] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[18:17:34.351] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[18:17:34.357] Using SSH config file "C:\Users\rajve\.ssh\config"
[18:17:34.357] Running script with connection command: "C:\windows\System32\OpenSSH\ssh.exe" -T -D 59294 -F "C:\Users\rajve\.ssh\config" "xxxx-workspace.devpod" bash
[18:17:34.360] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[18:17:39.450] "install" terminal received data: "[?25l[2J[m[He941df84d573: running
Found existing installation at /root/.vscode-server...
]0;C:\WINDOWS\System32\cmd.exe[?25hStarting VS Code CLI... "/root/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286" command-shell --cli-data-dir "/root/.vscode-server/cli" --on-port --on-host=127.0.0.1 --parent-process-id 13974 &> "/root/.vscode-server/.cli.ea1445cc7016315d0f5728f8e8b12a45dc0a7286.log" < /dev/null
printenv:"
[18:17:39.451] Got some output, clearing connection timeout
[18:17:39.468] "install" terminal received data: "[?25l    DEVPOD_WORKSPACE_UID=reancare-w-d6962
    HOSTNAME=90b35b57fce8
    YARN_VERSION=1.22.19
    PWD=/root
    HOME=/root
    REMOTE_CONTAINERS=true
    DEVPOD_WORKSPACE_ID=xxxx-workspace
    VSCODE_AGENT_FOLDER=/root/.vscode-server
    DEVPOD=true
    SHLVL=3
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    NODE_VERSION=18.12.0
    _=/bin/printenv
Removing old logfile at /root/.vscode-server/.cli.ea1445cc7016315d0f5728f8e8b12a45dc0a7286.log
Spawned remote CLI: 13994
ps: unrecognized option: p
BusyBox v1.35.0 (2024-05-16 22:46:25 UTC) multi-call binary.[27;1HUsage: ps Exec server process not found
[-o COL1,COL2=HEADER] [-T][30;1HShow list of processes[?25h

        -o COL1,COL2=HEADER     Select columns for display
        -T                      Show threads"
[18:17:39.477] "install" terminal received data: "e941df84d573: start
SSH_AUTH_SOCK====
DISPLAY====
listeningOn====
osReleaseId==alpine==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==0==
execServerToken==1a1111a1-a1a1-111a-aaaa-aa1a11111a11==
e941df84d573: end"
[18:17:39.477] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
listeningOn====
osReleaseId==alpine==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==0==
execServerToken==1a1111a1-a1a1-111a-aaaa-aa1a11111a11==

[18:17:39.478] Failed to parse remote port from server output
[18:17:39.481] Resolver error: Error: 

[18:17:39.872] "install" terminal received data: ""
[18:17:39.930] Opening exec server for ssh-remote+xxxx-workspace.devpod
[18:17:39.951] Initizing new exec server for ssh-remote+xxxx-workspace.devpod
[18:17:39.995] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0axxxx" and quality "stable" for server
[18:17:39.998] Install and start server if needed
[18:17:40.038] Opening exec server for ssh-remote+xxxx-workspace.devpod
[18:17:51.899] getPlatformForHost was canceled
[18:17:51.900] Exec server for ssh-remote+xxxx-workspace.devpod failed: Error: Connecting was canceled
[18:17:51.900] Existing exec server for ssh-remote+xxxx-workspace.devpod errored (Error: Connecting was canceled)
[18:17:51.901] Initizing new exec server for ssh-remote+xxxx-workspace.devpod
[18:17:51.901] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0axxxx" and quality "stable" for server
[18:17:51.903] Error opening exec server for ssh-remote+xxxx-workspace.devpod: Error: Connecting was canceled

**Comment by koudy500** [comment]
So? What is the solution? I have the same or very similar issue. when I run devpod-cli on vscode-remote-try-python (because I am learning how it works) but when I try to remove already existing  conteiner by `devpod delete vscode-remote-try-python` and after I run `devpod up github.com/microsoft/vscode-remote-try-python` it works.
But the issue occurs when container already exists and I try only `devpod up github.com/microsoft/vscode-remote-try-python` or `devpod up vscode-remote-try-python`, it launches the vscode and vscode is trying to ssh remote connect it fails. 

see below:

[12:41:49.830] SSH Resolver called for "ssh-remote+vscode-remote-try-python.devpod", attempt 1
[12:41:49.832] remote.SSH.useLocalServer = true
[12:41:49.833] remote.SSH.useExecServer = true
[12:41:49.833] remote.SSH.bindHost = {}
[12:41:49.833] remote.SSH.path = undefined
[12:41:49.833] remote.SSH.configFile = undefined
[12:41:49.833] remote.SSH.useFlock = true
[12:41:49.833] remote.SSH.lockfilesInTmp = false
[12:41:49.833] remote.SSH.localServerDownload = auto
[12:41:49.833] remote.SSH.remoteServerListenOnSocket = false
[12:41:49.834] remote.SSH.defaultExtensions = []
[12:41:49.834] remote.SSH.defaultExtensionsIfInstalledLocally = []
[12:41:49.834] remote.SSH.loglevel = 2
[12:41:49.834] remote.SSH.enableDynamicForwarding = true
[12:41:49.834] remote.SSH.enableRemoteCommand = false
[12:41:49.834] remote.SSH.serverPickPortsFromRange = {}
[12:41:49.834] remote.SSH.serverInstallPath = {}
[12:41:49.834] remote.SSH.permitPtyAllocation = false
[12:41:49.835] remote.SSH.preferredLocalPortRange = undefined
[12:41:49.835] remote.SSH.useCurlAndWgetConfigurationFiles = false
[12:41:49.835] remote.SSH.experimental.chat = false
[12:41:49.835] remote.SSH.experimental.enhancedSessionLogs = false
[12:41:49.839] VS Code version: 1.97.1
[12:41:49.839] Remote-SSH version: remote-ssh@0.117.1
[12:41:49.839] linux x64
[12:41:49.854] SSH Resolver called for host: vscode-remote-try-python.devpod
[12:41:49.854] Setting up SSH remote "vscode-remote-try-python.devpod"
[12:41:49.859] Acquiring local install lock: /tmp/vscode-remote-ssh-dab5ffcf-install.lock
[12:41:49.860] Looking for existing server data file at /home/pasekas/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dab5ffcf-e249dada235c2083c83813bd65b7f4707fb97b76-0.117.1-es/data.json
[12:41:49.861] No existing data file
[12:41:49.861] Using commit id "e249dada235c2083c83813bd65b7f4707fb97b76" and quality "stable" for server
[12:41:49.861] Extensions to install: 
[12:41:49.865] Install and start server if needed
[12:41:49.868] PATH: /home/pasekas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/pasekas/.local/share/JetBrains/Toolbox/scripts
[12:41:49.868] Checking ssh with "ssh -V"
[12:41:49.878] > OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024

[12:41:49.882] askpass server listening on /run/user/1000/vscode-ssh-askpass-9c16db4c55c088fccb695616e29247ce465643b5.sock
[12:41:49.882] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-41411c135dec4268434a2208efbdfc9b51c43fd4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45241","-o","ConnectTimeout=15","vscode-remote-try-python.devpod"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/pasekas/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dab5ffcf-e249dada235c2083c83813bd65b7f4707fb97b76-0.117.1-es/data.json"}
[12:41:49.882] Local server env: {"SSH_AUTH_SOCK":"/tmp/ssh-oQ5b9XdAYpQZ/agent.3237","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/183/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-9c16db4c55c088fccb695616e29247ce465643b5.sock"}
[12:41:49.888] Spawned 13112
[12:41:49.889] Using connect timeout of 17 seconds
[12:41:49.965] > local-server-1> Running ssh connection command: ssh -v -T -D 45241 -o ConnectTimeout=15 vscode-remote-try-python.devpod
[12:41:49.968] > local-server-1> Spawned ssh, pid=13120
[12:41:49.971] stderr> OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024
[12:41:56.463] stderr> 12:41:56 info Waiting for devpod agent to come up...
[12:42:02.646] stderr> 12:42:02 info Waiting for devpod agent to come up...
[12:42:04.985] stderr> Connection timed out during banner exchange
[12:42:04.985] stderr> Connection to UNKNOWN port 65535 timed out
[12:42:04.987] > local-server-1> ssh child died, shutting down
[12:42:04.995] Local server exit: 0
[12:42:04.996] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 45241 -o ConnectTimeout=15 vscode-remote-try-python.devpod
local-server-1> Spawned ssh, pid=13120
OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024
12:41:56 info Waiting for devpod agent to come up...
12:42:02 info Waiting for devpod agent to come up...
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-1> ssh child died, shutting down

[12:42:04.996] WARN: $PLATFORM is undefined in installation script output.  Errors may be dropped.
[12:42:04.999] Resolver error: Error: The connection timed out
	at y.Offline (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:739101)
	at /home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:735417
	at t.handleInstallOutput (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:735732)
	at e (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:789804)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:812522
	at async t.withShowDetailsEvent (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:816213)
	at async /home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:786516
	at async T (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:784571)
	at async t.resolveWithLocalServer (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:786068)
	at async R (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:809398)
	at async t.resolve (/home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:813614)
	at async /home/pasekas/.vscode/extensions/ms-vscode-remote.remote-ssh-0.117.1/out/extension.js:2:1099250
[12:42:05.006] ------




[12:42:05.007]  ---------- [Session Summary] ----------- 
[12:42:05.007] [OfflineError]: Error: OfflineError (The connection timed out)
[12:42:05.007]  ---------------------------------------- 

what I dont understand is:
why ssh died?
what is banner exchange?
how is possible that the container is not behaving the same when I created firstly created it?
