### ISSUE TITLE
ssh EXOENT issue with windows WSL2

### ISSUE THREAD

**Issue by rbavery** [loft-sh/devpod#789]
**What happened?**  

I installed devpod on my wsl ubuntu partition and ran this tutorial https://devpod.sh/docs/developing-in-workspaces/create-a-workspace#via-devpod-cli

This error occurred in vscode after running `devpod up github.com/microsoft/vscode-remote-try-node`:

```
[14:17:59.498] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[14:17:59.500] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[14:17:59.500] Checking ssh with "C:\Windows\ssh.exe -V"
[14:17:59.501] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[14:17:59.501] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[14:17:59.502] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[14:17:59.502] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[14:17:59.503] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[14:17:59.503] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[14:17:59.526] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[14:17:59.529] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 53788 "vscode-remote-try-node.devpod" bash
[14:17:59.531] Terminal shell path: C:\Windows\System32\cmd.exe
[14:17:59.763] > ssh: Could not resolve hostname vscode-remote-try-node.devpod: No such host is known.
> The process tried to write to a nonexistent pipe.
> ]0;C:\Windows\System32\cmd.exe
[14:17:59.764] Got some output, clearing connection timeout
[14:18:01.030] "install" terminal command done
[14:18:01.031] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exe
[14:18:01.031] Received install output: ]0;C:\Windows\System32\cmd.exe
[14:18:01.031] Failed to parse remote port from server output
[14:18:01.033] Resolver error: Error: 
	at g.Create (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:640937)
	at t.handleInstallOutput (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:638303)
	at t.tryInstall (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:760218)
	at async c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:720757
	at async t.withShowDetailsEvent (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:724063)
	at async I (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:717728)
	at async t.resolve (c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:721434)
	at async c:\Users\ryanb\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:905238
[14:18:01.036] ------
```

**What did you expect to happen instead?**  
To  connect my Windows Vscode to my docker container started with devpod. I can connect to other containers that are not started with devpod.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

On WSL 2:

```
curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
devpod provider add docker
devpod up github.com/microsoft/vscode-remote-try-node
```

**Local Environment:**  
- DevPod Version: v0.4.0
- Operating System: linux (on wsl 2)
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: NA
- Kubernetes Provider: NA
- Local/remote provider: docker
- Custom provider: NA

**Anything else we need to know?**  

I initially tried to install devpod on Windows and then use it to manage devcontainers on WSL2. But I couldn't get it to work from the WSL terminal.  

```
-> % devpod
/mnt/c/Users/ryanb/AppData/Roaming/sh.loft.devpod/bin/devpod: 2: C:\Program Files\DevPod\devpod-cli.exe: not found
```

I found this section on wsl2, but it doesn't make it clea how I could set devpod home from within the windows gui https://devpod.sh/docs/developing-in-workspaces/create-a-workspace#via-devpod-desktop-application

And when I try to do so from my WSL partition I get the same error:

```
rave@studio2 [14:54:00] [~]
-> % DEVPOD_HOME=/mnt/c/Users/ryanb/
(base)
rave@studio2 [14:54:22] [~]
-> % devpod
/mnt/c/Users/ryanb/AppData/Roaming/sh.loft.devpod/bin/devpod: 2: C:\Program Files\DevPod\devpod-cli.exe: not found
```

**Comment by pascalbreuninger** [comment]
Hi @rbavery , thanks for opening the issue. We currently don't support linking the cli binary into WSL from the desktop app. Based on your logs it looks like the `devpod` in `%PATH%` is based on the one from the Desktop app. If you remove the devpod folder (`%APP_DIR%/sh.loft.devpod/bin`) from your PATH and only keep the cli version inside of wsl, it _should_ work.

**Comment by rbavery** [comment]
ah thank you, I'll try using devpod from the CLI only

**Comment by Neurrone** [comment]
@rbavery did you manage to resolve this? I'm having the same issue, trying to get VS Code on Windows to connect to a devpod in WSL2.

**Comment by Neurrone** [comment]
I managed to figure this out.

Devpod creates a new entry in ~/.ssh/config on WSL2, where I was running it. I needed to copy that block over to the ssh config file on Windows so that VS Code is able to connect to the devpod container.

On the windows SSH config, change the proxy command to

```
    ProxyCommand wsl -d <distro> -- <command from the WSL2 ssh config proxy command>
```

Don't put any quotes after the distribution name.
