### ISSUE TITLE
SSH Tunnel : TimeOut issue with vscode

### ISSUE THREAD

**Issue by MasqAs** [loft-sh/devpod#849]
**What happened?**  
A timeout problem appears on vscode when it is opened.

```bash
[19:21:13.659] Resolver error: **Error: The connection timed out**
	at g.Offline (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642754)
	at /Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:638823
	at t.handleInstallOutput (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:639138)
	at e (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/Test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[19:21:13.666] ------
```

**What did you expect to happen instead?**  
To be able to customize the timeout value used in the command : 

```bash
ssh -v -T -D 64056 -o ConnectTimeout=15 vxlan-evpn.devpod
```

**How can we reproduce the bug?** (as minimally and precisely as possible)
Creation of a workspace on an EC2 instance with a weak FAI connection.

My *`devcontainer.json`*:
```
{
	"name": "ContainerLab",
    "dockerComposeFile": "docker-compose.yml",
    "service": "containerlab",

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [50080],

	// Mount worspace on container
	"workspaceFolder": "/workspace",
}
```

**Local Environment:**  
- DevPod Version: v0.4.2
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider:  aws

**Anything else we need to know?**  

The problem seems to be linked to the "Timeout" argument used when creating the tunnel via the SSH command.
On a separate terminal, using the command: `ssh -v -T -D 64056 -o ConnectTimeout=60 vxlan-evpn.devpod`
seems to work.

I looked in the settings or in the documentation, but I couldn't find anything about customizing this command.

**Comment by hrittikhere** [comment]
There's a `remote.SSH.connectTimeout` option on vscode. Did you try that?  That worked for me :) 
![image](https://github.com/loft-sh/devpod/assets/67012359/7606871b-7443-4c48-b145-87d66357eca2)

**Comment by MasqAs** [comment]
Thank you for your reply!
I was stuck on the fact that the configuration was forced on DevPod that I did not think to look at the configurations on VSCode.
Thanks, it works.
